### ISSUE TITLE
Gem googleauth breaks support for Ruby 2.2

### ISSUE THREAD

**Issue by xv-jesus-g** [fluent-plugins-nursery/fluent-plugin-bigquery#174]
## Environments

- fluentd version: 2.3.6-0 (td-agent)
- plugin version: 1.2.0
- ruby version: 2.2 

## Expected Behavior

Works

## Actual Behavior
Doesn't work, the latest version of  ```googleauth``` includes ```quiggly heredoc```, only compatible with Ruby 2.3.
As for your version support

plugin version | fluentd version | ruby version
-- | -- | --
v0.4.x | 0.12.x | 2.0 or later
v1.x.x | 0.14.x or later | 2.2 or later
v2.x.x | 0.14.x or later | 2.3 or later

It should be working fine (actually it suddenly broke or deployment).

Our work around is to install googleauth:0.7.1 (an older version) before we install fluent-plugin-bigquery:1.2.0

Notice from Googleauth: https://github.com/googleapis/google-auth-library-ruby
They only support Ruby 2.3+
But the 7.1 works fine.

Please either update the Gem so it uses < googleauth:8.0, or update the supported versions of Ruby.

**Comment by joker1007** [comment]
I think that updating this plugin and ruby is best solution.
If it is difficult, you can use `--gemfile`option of fluentd command.

1. Write Gemfile 
`gem "googleauth", "< 8.0"` with other plugin gems
1. Exec `bundle install`
1.  Launch fluentd with `--gemfile` option.
