### ISSUE TITLE
How can I output the entire json object as a string to BigQuery

### ISSUE THREAD

**Issue by huihuiy02** [fluent-plugins-nursery/fluent-plugin-bigquery#183]
Just wondering any way to push the json object as a string to Bigquery in Fluentd?

**Comment by joker1007** [comment]
Probably, you can use [record_transformer](https://docs.fluentd.org/filter/record_transformer)  plugin.

For example, record_transformer converts entire record to `{"payload": <jsonized record>`} and fluent-plugin-bigquery inserts to table that has only `payload:STRING` column.

```
<filter sample.*>
  @type record_transformer
  enable_ruby
  <record>
    payload ${record.to_json}
  </record>
</filter>

<match sample.*>
  @type bigquery_insert

  auth_method private_key   # default
  email xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxx@developer.gserviceaccount.com
  private_key_path /home/username/.keys/00000000000000000000000000000000-privatekey.p12
  # private_key_passphrase notasecret # default

  project yourproject_id
  dataset yourdataset_id
  table   tablename

  schema [
    {"name": "payload", "type": "STRING"},
  ]
</match>
```

(This configuration is just sample)

**Comment by huihuiy02** [comment]
Thanks for the quick response. I have tried this and it shows error as below 

> nse::InsertError:0x00007f2dfb964850 @errors=[#<Google::Apis::BigqueryV2::ErrorProto:0x00007f2dfb963f90 @debug_info=\"\", @location=\"log\", @message=\"no such field.\", @reason=\"invalid\">], @index=495>]"


My json object is a nested json, so it seems the output plugin just parse the nested json and then try to load each field to Bigquery.  

My config looks like below 
`
  <source>
    @type kafka_group
    brokers "kafka-1:9092,kafka-2:9092,kafka-3:9092"
    consumer_group "fluentd"
    topics "edge"
    format "text"
  </source>
  <filter edge>
    @type record_transformer
    enable_ruby
    renew_record true
    keep_keys payload
    <record>
      payload ${record.to_json}
    </record>
  </filter>
  <match edge-east-server>
    @type bigquery_insert
    auth_method compute_engine
    project "xxxx"
    dataset "xxxx"
    table "edge_server_aaa"
    fetch_schema true
    <buffer>
      @type "file"
      path "/data/bigquery.edge.buffer"
      flush_interval 0.1
      queue_length_limit 4096
      flush_thread_count 16
      chunk_records_limit 1000
    </buffer>
  </match>

`

My json data looks like 
`{ {\\\"@timestamp\\\":\\\"2020-02-25T13:04:49.853Z\\\",\\\"@metadata\\\":{\\\"beat\\\":\\\"filebeat\\\",\\\"type\\\":\\\"doc\\\",\\\"version\\\":\\\"6.7.2\\\",\\\"topic\\\":\\\"edge-server\\\"}`   The json schema is keep changing, that's why I want to load the entire json as a strong in 1 column.

**Comment by huihuiy02** [comment]
Wondering if this is related how does the plugin generate the rows in [multi_json](https://github.com/fluent-plugins-nursery/fluent-plugin-bigquery/blob/master/lib/fluent/plugin/out_bigquery_insert.rb#L80)

**Comment by joker1007** [comment]
Does `edge_server_aaa` has `payload` column?
It seems not to have the column for me.

**Comment by huihuiy02** [comment]
Yes, we use the record_transformer configuration to add the `payload` column.  I mean it may be due to the error when bigquery load the nested json.  It is trying to load ['payload]['xxx'] into biguquery which results in the error.    As the configuration listed
```
  <filter edge>
    @type record_transformer
    enable_ruby
    renew_record true
    keep_keys payload
    <record>
      payload ${record.to_json}
    </record>
  </filter>
```

I renew the entire record as one field 'payload' to include the entire json object. Much appreicate for your help.   It always show error `no such field' which means it tries to load each field into BigQuery instead of loading the `payload` as a single column.

**Comment by joker1007** [comment]
Hmm...
I'm very sorry, I can't guess what causes the error.
If the `payload` column becomes a string value, bigquery plugin should be able to send it properly.
I suggest [stdout filter](https://docs.fluentd.org/filter/stdout) in order to see actual records sent by bigquery plugin.
It's my last resort.

**Comment by huihuiy02** [comment]
It works now.   I have replaced all the double quotes in the filed and then it works. 

The wired thing is still showing same error log, however, it has been inserted into BigQuery successfully.
