### ISSUE TITLE
Unknown output plugin 'bigquery_insert'

### ISSUE THREAD

**Issue by nikita-pivovarov** [fluent-plugins-nursery/fluent-plugin-bigquery#218]
## Environments

Ubuntu Jammy
- td-agent: 4.5.2
- fluentd version: 1.16.5
- plugin version: 3.1.0

## Configuration
```
<match dammy>
  @type           bigquery_insert

   auth_method json_key
```

## Expected Behavior

Should work

## Actual Behavior
Getting error Unknown output plugin 'bigquery_insert'
## Log (if you have)
```
td-agent --dry-run
2024-12-20 12:31:15 +0000 [error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::NotFoundPluginError error="Unknown output plugin 'bigquery_insert'. Run 'gem search -rd fluent-plugin' to find plugins"
```

**Comment by joker1007** [comment]
I'm sorry,  I cannot reproduce the error message.
Could you submit the complete syntax config, and all logs until fluentd stopped?

**Comment by nikita-pivovarov** [comment]
False alarm, this is because of wrong gem path

Thanks for quick response!
